# Generated by Django 2.1.7 on 2019-04-28 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floravale_bus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='description',
            field=models.CharField(default='first description', max_length=256),
            preserve_default=False,
        ),
    ]
